postgresql-11: Initial attempt to fix upgrade(). This code works for now, but needs a lot of error checking, etc. Current version only does the upgrade with symlink method.

diff --git a/rpm/redhat/11/postgresql/master/postgresql-11-setup b/rpm/redhat/11/postgresql/master/postgresql-11-setup
--- a/rpm/redhat/11/postgresql/master/postgresql-11-setup
+++ b/rpm/redhat/11/postgresql/master/postgresql-11-setup
@@ -14,6 +14,10 @@ PGENGINE=xxxx
 PREVMAJORVERSION=10
 # PREVPGENGINE is the directory containing the previous postmaster executable
 PREVPGENGINE=/usr/pgsql-$PREVMAJORVERSION/bin
+# PREVDATADIR is the directory containing the previous postmaster executable
+PREVDATADIR=/var/lib/pgsql/$PREVMAJORVERSION/data
+
+# TODO: Provide a conf file that can override these settings
 
 # The second parameter is the new database version, i.e. $PGMAJORVERSION in this case.
 # Use  "postgresql-$PGMAJORVERSION" service, if not specified.
@@ -64,7 +68,7 @@ Environment:
 # note that these options are useful at least for help2man processing
 case "$1" in
     --version)
-	echo "PostgreSQL setup scrip for version $PGVERSION"
+	echo "PostgreSQL setup script for version $PGVERSION"
         exit 0
         ;;
     --help|--usage)
@@ -167,20 +171,14 @@ initdb(){
 
 upgrade(){
     # must see previous version in PG_VERSION
-    if [ ! -f "$PGDATA/PG_VERSION" -o \
-         x`cat "$PGDATA/PG_VERSION"` != x"$PREVMAJORVERSION" ]
+    if [ ! -f "$PREVDATADIR/PG_VERSION" -o \
+         x`cat "$PREVDATADIR/PG_VERSION"` != x"$PREVMAJORVERSION" ]
     then
         echo
         echo $"Cannot upgrade because the database in $PGDATA is not of"
         echo $"compatible previous version $PREVMAJORVERSION."
         echo
         exit 1
-    fi
-    if [ ! -x "$PGENGINE/pg_upgrade" ]; then
-        echo
-        echo $"Please install the postgresql-upgrade RPM."
-        echo
-        exit 5
     fi
 
     # Set up log file for pg_upgrade
@@ -190,37 +188,41 @@ upgrade(){
     chmod go-rwx "$PGUPLOG"
     [ -x /sbin/restorecon ] && /sbin/restorecon "$PGUPLOG"
 
-    # Move old DB to PGDATAOLD
-    PGDATAOLD="${PGDATA}-old"
-    rm -rf "$PGDATAOLD"
-    mv "$PGDATA" "$PGDATAOLD" || exit 1
+    # Make sure that the user initdb'ed the new cluster:
+    if [ ! -f "$PGDATA/PG_VERSION" ]
+    then
+        echo
+        echo $"Please initialize the new cluster before upgrading."
+        echo $"You can run this script with the ''initdb'' parameter:"
+	echo $""
+	echo $"$PGENGINE/postgresql-$PGVERSION-setup initdb"
+        echo
+        exit 1
+    fi
 
-    # Create configuration file for upgrade process
-    HBA_CONF_BACKUP="$PGDATAOLD/pg_hba.conf.postgresql-setup.`date +%s`"
+    # Copy the current pg_hba.conf file to new cluster:
+
     HBA_CONF_BACKUP_EXISTS=0
 
-    if [ ! -f $HBA_CONF_BACKUP ]; then
-        mv "$PGDATAOLD/pg_hba.conf" "$HBA_CONF_BACKUP"
+        cp "$PREVDATADIR/pg_hba.conf" "$PGDATA/"
         HBA_CONF_BACKUP_EXISTS=1
 
         # For fluent upgrade 'postgres' user should be able to connect
         # to any database without password.  Temporarily, no other type
         # of connection is needed.
-        echo "local all postgres ident" > "$PGDATAOLD/pg_hba.conf"
-    fi
+        echo "local all postgres peer" > "$PREVDATADIR/pg_hba.conf"
 
     echo -n $"Upgrading database: "
 
     # Create empty new-format database
-    if perform_initdb; then
+#    if perform_initdb; then
         # Do the upgrade
         $SU -l postgres -c "$PGENGINE/pg_upgrade \
                         '--old-bindir=$PREVPGENGINE' \
                         '--new-bindir=$PGENGINE' \
-                        '--old-datadir=$PGDATAOLD' \
+                        '--old-datadir=$PREVDATADIR' \
                         '--new-datadir=$PGDATA' \
                         --link \
-                        '--old-port=$PGPORT' '--new-port=$PGPORT' \
                         --user=postgres \
                         $PGSETUP_PGUPGRADE_OPTIONS" \
                                 >> "$PGUPLOG" 2>&1 < /dev/null
@@ -228,26 +230,18 @@ upgrade(){
             # pg_upgrade failed
             script_result=1
         fi
-    else
-        # initdb failed
-        script_result=1
-    fi
-
-    # Move back the backed-up pg_hba.conf regardless of the script_result.
-    if [ x$HBA_CONF_BACKUP_EXISTS = x1 ]; then
-        mv -f "$HBA_CONF_BACKUP" "$PGDATAOLD/pg_hba.conf"
-    fi
+#    else
+#        # initdb failed
+#        script_result=1
+#    fi
 
     if [ $script_result -eq 0 ]; then
         echo $"OK"
         echo
-        echo $"The configuration files were replaced by default configuration."
-        echo $"The previous configuration and data are stored in folder"
-        echo $PGDATAOLD.
+        echo $"pg_hba.conf configuration file of the new cluster was replaced by the one in the old cluster."
     else
         # Clean up after failure
         rm -rf "$PGDATA"
-        mv "$PGDATAOLD" "$PGDATA"
         echo $"failed"
     fi
     echo
