postgrsql-11: Add check_upgrade() as a new option, so that users can perform a check before the actual upgrade

diff --git a/rpm/redhat/11/postgresql/master/postgresql-11-setup b/rpm/redhat/11/postgresql/master/postgresql-11-setup
--- a/rpm/redhat/11/postgresql/master/postgresql-11-setup
+++ b/rpm/redhat/11/postgresql/master/postgresql-11-setup
@@ -4,7 +4,7 @@
 
 # PGVERSION is the full package version, e.g., 11.0
 # Note: the specfile inserts the correct value during package build
-PGVERSION=xxxx
+PGVERSION=11
 # PGMAJORVERSION is major version, e.g., 11 (this should match PG_VERSION)
 PGMAJORVERSION=`echo "$PGVERSION" | sed 's/^\([0-9]*\.[0-9]*\).*$/\1/'`
 # PGENGINE is the directory containing the postmaster executable
@@ -36,7 +36,7 @@ then
 fi
 
 USAGE_STRING=$"
-Usage: $0 {initdb|upgrade} [SERVICE_NAME]
+Usage: $0 {initdb|check_upgrade|upgrade} [SERVICE_NAME]
 
 Script is aimed to help sysadmin with basic database cluster administration.
 
@@ -48,6 +48,8 @@ string is used when no SERVICE_NAME is explicitly passed.
 Available operation mode:
   initdb        Create a new PostgreSQL database cluster.  This is usually the
                 first action you perform after PostgreSQL server installation.
+  check_upgrade	Checks whether the old cluster can be upgraded to the new version
+		or not.
   upgrade	Upgrade PostgreSQL database cluster to be usable with new
                 server.  Use this if you upgraded your PostgreSQL server to
                 newer major version (currently from $PREVMAJORVERSION \
@@ -169,7 +171,7 @@ initdb(){
     fi
 }
 
-upgrade(){
+check_upgrade(){
     # must see previous version in PG_VERSION
     if [ ! -f "$PREVDATADIR/PG_VERSION" -o \
          x`cat "$PREVDATADIR/PG_VERSION"` != x"$PREVMAJORVERSION" ]
@@ -212,6 +214,38 @@ upgrade(){
         # of connection is needed.
         echo "local all postgres peer" > "$PREVDATADIR/pg_hba.conf"
 
+    echo -n $"Performing upgrade check: "
+
+        # Do the upgrade
+        $SU -l postgres -c "$PGENGINE/pg_upgrade \
+                        '--old-bindir=$PREVPGENGINE' \
+                        '--new-bindir=$PGENGINE' \
+                        '--old-datadir=$PREVDATADIR' \
+                        '--new-datadir=$PGDATA' \
+                        --check \
+                        --user=postgres \
+                        $PGSETUP_PGUPGRADE_OPTIONS" \
+                                >> "$PGUPLOG" 2>&1 < /dev/null
+        if [ $? -ne 0 ]; then
+            # pg_upgrade failed
+            script_result=1
+        fi
+    if [ $script_result -eq 0 ]; then
+        echo $"OK"
+    else
+        # Clean up after failure
+	echo "Upgrade failed. Removing the new cluster. Please re-initdb the new cluster."
+        rm -rf "$PGDATA"
+        echo $"failed"
+    fi
+    echo
+    echo $"See $PGUPLOG for details."
+}
+
+
+upgrade(){
+# Perform the upgrade check first:
+check_upgrade
     echo -n $"Upgrading database: "
 
         # Do the upgrade
@@ -248,6 +282,9 @@ case "$1" in
         ;;
     upgrade)
         upgrade
+        ;;
+    check_upgrade)
+        check_upgrade
         ;;
     *)
         echo >&2 "$USAGE_STRING"
