Bring pgpool init script in line with pgpool community init script

diff --git a/rpm/redhat/9.4/pgpool-II/EL-6/pgpool.init b/rpm/redhat/9.4/pgpool-II/EL-6/pgpool.init
--- a/rpm/redhat/9.4/pgpool-II/EL-6/pgpool.init
+++ b/rpm/redhat/9.4/pgpool-II/EL-6/pgpool.init
@@ -4,7 +4,7 @@
 # chkconfig: - 74 33
 # description: Starts and stops the pgpool daemon
 # processname: pgpool
-# pidfile:	/var/run/pgpool.pid
+# pidfile:  /var/run/pgpool.pid
 #
 # v1.0.0 Devrim GUNDUZ <devrim@gunduz.org>
 # - Initial version of Red Hat / Fedora init script
@@ -40,7 +40,7 @@ TYPESET=`typeset -f|grep "declare"`
 NAME=`basename $0`
 if [ ${NAME:0:1} = "S" -o ${NAME:0:1} = "K" ]
 then
-	NAME=${NAME:3}
+    NAME=${NAME:3}
 fi
 
 # For SELinux we need to use 'runuser' not 'su'
@@ -52,96 +52,99 @@ else
 fi
 
 # Set defaults for configuration variables
+PGPOOLUSER=postgres
 PGPOOLENGINE=/usr/pgpool-9.4/bin
 PGPOOLDAEMON=$PGPOOLENGINE/pgpool
 PGPOOLCONF=/etc/pgpool-II-94/pgpool.conf
 PGPOOLPIDDIR=/var/run/pgpool-II-94
 PGPOOLLOG=/var/log/pgpool-II-94.log
 
+lockfile="/var/lock/subsys/${NAME}"
+pidfile="$PGPOOLPIDDIR/pgpool.pid"
+
 test -x $PGPOOLDAEMON || exit 5
 
 # Check whether the config file exists or not
 if [ ! -r $PGPOOLCONF ]
 then
-	echo "$PGPOOLCONF not found"
-	RETVAL=1
-	failure	
-	exit
+    echo "$PGPOOLCONF not found"
+    RETVAL=1
+    failure
+    exit
 fi
 
 # Create the log file if it does not exist
 if [ ! -x $PGPOOLLOG ]
 then
-	touch $PGPOOLLOG
-	chown postgres: $PGPOOLLOG
+    touch $PGPOOLLOG
+    chown postgres: $PGPOOLLOG
 fi
 
 if [ ! -d $PGPOOLPIDDIR ]
 then
-	mkdir $PGPOOLPIDDIR
-	chown postgres: $PGPOOLPIDDIR
+    mkdir $PGPOOLPIDDIR
+    chown postgres: $PGPOOLPIDDIR
 fi
 
 script_result=0
 
 start(){
-	pid=`pidof -s "$PGPOOLDAEMON"`
-	if [ $pid ]
-	then
-		echo "pgpool is already running with pid $pid"
-		failure "$PGPOQL_START"
-		echo
-		script_result=1
-		exit 1
-	fi
+    pid=`pidof -s "$PGPOOLDAEMON"`
+    if [ $pid ]
+    then
+        echo "pgpool is already running with pid $pid"
+        failure "$PGPOQL_START"
+        echo
+        script_result=1
+        exit 1
+    fi
 
-	PGPOOL_START=$"Starting ${NAME} service: "
+    PGPOOL_START=$"Starting ${NAME} service: "
 
-	echo -n "$PGPOOL_START"
+    echo -n "$PGPOOL_START"
 
-	$SU -l postgres -c "$PGPOOLDAEMON -f $PGPOOLCONF $OPTS & " >> "$PGPOOLLOG" 2>&1 < /dev/null
-	sleep 2
+    $SU -l postgres -c "$PGPOOLDAEMON -f $PGPOOLCONF $OPTS & " >> "$PGPOOLLOG" 2>&1 < /dev/null
+    sleep 2
 
-	pid=`pidof -s "$PGPOOLDAEMON"`
-	if [ $pid ] 
-	then
-		success "$PGPOOL_START"
-		touch /var/lock/subsys/${NAME}
-		echo
-	else
-		failure "$PGPOQL_START"
-		echo
-		script_result=1
-	fi
+    pid=`pidof -s "$PGPOOLDAEMON"`
+    if [ $pid ]
+    then
+        success "$PGPOOL_START"
+        touch "${lockfile}"
+        echo
+    else
+        failure "$PGPOQL_START"
+        echo
+        script_result=1
+    fi
 }
 
 stop(){
-	echo -n $"Stopping ${NAME} service: "
+    echo -n $"Stopping ${NAME} service: "
         if [ $UID -ne 0 ]; then
-                RETVAL=1
-                failure
+            RETVAL=1
+            failure
         else
-		killproc /usr/bin/pgpool
-#		$PGPOOLDAEMON stop & >> "$PGPOOLLOG" 2>&1 < /dev/null
-                RETVAL=$?
-                [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/${NAME}
+            $SU -l $PGPOOLUSER -c "$PGPOOLDAEMON -f $PGPOOLCONF -m fast stop" >> "$PGPOOLLOG" 2>&1 < /dev/null
+            RETVAL=$?
+            [ $RETVAL -eq 0 ] && rm -f ${lockfile}
         fi;
         echo
         return $RETVAL
 }
 
 switch() {
-	echo -n $"Sending switchover request to $NAME "
-	$PGPOOLDAEMON -f $PGPOOLCONF switch >> "$PGPOOLLOG" 2>&1 < /dev/null
-	RETVAL=$?
-	echo
-	if [ $RETVAL -eq 0 ] 
-	then
-		echo_success
-	else
-		echo_failure
-	fi
-	echo
+    echo -n $"Sending switchover request to $NAME "
+    $PGPOOLDAEMON -f $PGPOOLCONF switch >> "$PGPOOLLOG" 2>&1 < /dev/null
+    RETVAL=$?
+    echo
+    if [ $RETVAL -eq 0 ]
+    then
+        echo_success
+    else
+        echo_failure
+    fi
+    echo
 }
 
 restart(){
@@ -150,23 +153,23 @@ restart(){
 }
 
 reload(){
-	echo -n $"Reloading ${NAME}: "
+    echo -n $"Reloading ${NAME}: "
 
-	if [ -n "`pidfileofproc $PGPOOLDAEMON`" ] ; then
-		killproc $PGPOOLDAEMON -HUP
-	else
-		failure $"Reloading ${NAME}"
-	fi
-	RETVAL=$?
-	echo
+    if [ -n "`pidofproc -p $pidfile $PGPOOLDAEMON`" ] ; then
+        $SU -l $PGPOOLUSER -c "$PGPOOLDAEMON -f $PGPOOLCONF reload" >> "$PGPOOLLOG" 2>&1 < /dev/null
+    else
+        failure "Reloading ${NAME}"
+    fi
+    RETVAL=$?
+    echo
 }
 
 condrestart(){
-	[ -e /var/lock/subsys/${NAME} ] && restart
+    [ -e "${lockfile}" ] && restart
 }
 
 condstop(){
-	[ -e /var/lock/subsys/${NAME} ] && stop
+    [ -e "${lockfile}" ] && stop
 }
 
 # See how we were called.
