PostgreSQL 19: Do not remove new PGDATA after upgrade attempt. Otherwise we will lose the error messages

diff --git a/rpm/redhat/main/non-common/postgresql-19/main/postgresql-19-setup b/rpm/redhat/main/non-common/postgresql-19/main/postgresql-19-setup
--- a/rpm/redhat/main/non-common/postgresql-19/main/postgresql-19-setup
+++ b/rpm/redhat/main/non-common/postgresql-19/main/postgresql-19-setup
@@ -48,12 +48,12 @@ fi
 if [ $# -gt 3 ]
 then
     echo "Warning: too many arguments ($# given, 3 expected). Extra arguments will be ignored." >&2
-    echo "HINT: These will be discarded. Set PGSETUP_INITDB_OPTIONS in /etc/sysconfig/postgresql-${PGMAJORVERSION}-setup instead." > &2
+    echo "HINT: These will be discarded. Set PGSETUP_INITDB_OPTIONS in /etc/sysconfig/postgresql-${PGMAJORVERSION}-setup instead." >&2
     echo "Usage: $0 {initdb|check_upgrade|upgrade} [SERVICE_NAME] [OLD_SERVICE_NAME]" >&2
 fi
 
 USAGE_STRING=$"
-Usage: $0 {initdb|check_upgrade|upgrade} [SERVICE_NAME]
+Usage: $0 {initdb|check_upgrade|upgrade} [SERVICE_NAME] [OLD_SERVICE_NAME]
 
 Script is aimed to help sysadmin with basic database cluster administration.
 
@@ -278,8 +278,7 @@ upgrade(){
         echo
         echo $"See $PGUPLOG for details."
         restore_pg_hba
-        rm -rf "$PGDATA"
-        echo "Upgrade check failed. Removing the new cluster. Please re-initdb the new cluster."
+        echo "Upgrade check failed. Please re-initdb the new cluster after analyzing the error."
         script_result=1
         return
     fi
@@ -300,7 +299,6 @@ upgrade(){
     if [ $? -ne 0 ]; then
         # pg_upgrade failed -- restore pg_hba.conf so old cluster remains usable
         restore_pg_hba
-        rm -rf "$PGDATA"
         echo $"failed"
         script_result=1
     else
