more fixes

diff --git a/rpm/redhat/9.5/pgpool-II/F-22/pgpool.init b/rpm/redhat/9.5/pgpool-II/F-22/pgpool.init
--- a/rpm/redhat/9.5/pgpool-II/F-22/pgpool.init
+++ b/rpm/redhat/9.5/pgpool-II/F-22/pgpool.init
@@ -72,10 +72,10 @@ text -x $PGPOOLDAEMON || exit 5
 # Check whether the config file exists or not
 if [ ! -r $PGPOOLCONF ]
 then
-	echo "$PGPOOLCONF not found"
-	RETVAL=1
-	failure	
-	exit
+    echo "$PGPOOLCONF not found"
+    echo_failure
+    echo
+    exit 1
 fi
 
 # Create the log file if it does not exist
@@ -94,49 +94,51 @@ fi
 script_result=0
 
 start(){
-	pid=`pidof -s "$PGPOOLDAEMON"`
-	if [ $pid ]
-	then
-		echo "pgpool is already running with pid $pid"
-		failure "$PGPOOL_START"
-		echo
-		script_result=1
-		exit 1
-	fi
+    PGPOOL_START=$"Starting ${NAME} service: "
 
-	PGPOOL_START=$"Starting ${NAME} service: "
+    echo -n "$PGPOOL_START"
+    pid="`pidofproc -p "$pidfile" -s "$PGPOOLDAEMON"`"
+    if [ -n "$pid" ] ; then
+        echo -n "pgpool is already running with pid $pid "
+        echo_failure
+        script_result=1
+    else
 
-	echo -n "$PGPOOL_START"
+        $SU -l $PGPOOLUSER -c "$PGPOOLDAEMON -f $PGPOOLCONF $OPTS & " >> "$PGPOOLLOG" 2>&1 < /dev/null
+        sleep 2
 
-	$SU -l postgres -c "$PGPOOLDAEMON -f $PGPOOLCONF $OPTS & " >> "$PGPOOLLOG" 2>&1 < /dev/null
-	sleep 2
-
-	pid=`pidof -s "$PGPOOLDAEMON"`
-	if [ $pid ] 
-	then
-		success "$PGPOOL_START"
-		touch "${lockfile}"
-		echo
-	else
-		failure "$PGPOOL_START"
-		echo
-		script_result=1
-	fi
+        pid="`pidofproc -p "$pidfile" -s "$PGPOOLDAEMON"`"
+        if [ -n "$pid" ] ; then
+            echo_success
+            touch "$lockfile"
+        else
+            echo_failure
+            script_result=1
+        fi
+    fi
+    echo
 }
 
 stop(){
-	echo -n $"Stopping ${NAME} service: "
-        if [ $UID -ne 0 ]; then
-                RETVAL=1
-                failure
+    PGPOOL_STOP=$"Stopping ${NAME} service: "
+
+    echo -n "$PGPOOL_STOP"
+    if [ -e "$lockfile" ] ; then
+
+        $SU -l $PGPOOLUSER -c "$PGPOOLDAEMON -f $PGPOOLCONF -m fast stop" >> "$PGPOOLLOG" 2>&1 < /dev/null
+
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ] ; then
+            echo_success
+            rm -f "$lockfile"
         else
-		killproc /usr/bin/pgpool
-#		$PGPOOLDAEMON stop & >> "$PGPOOLLOG" 2>&1 < /dev/null
-                RETVAL=$?
-                [ $RETVAL -eq 0 ] && rm -f ${lockfile}
-        fi;
-        echo
-        return $RETVAL
+            echo_failure
+            script_result=1
+        fi
+    else
+        echo_success
+    fi
+    echo
 }
 
 restart(){
@@ -145,15 +147,25 @@ restart(){
 }
 
 reload(){
-	echo -n $"Reloading ${NAME}: "
+    PGPOOL_RELOAD=$"Reloading ${NAME} configuration: "
 
-	if [ -n "`pidfileofproc $PGPOOLDAEMON`" ] ; then
-		killproc $PGPOOLDAEMON -HUP
-	else
-		failure $"Reloading ${NAME}"
-	fi
-	RETVAL=$?
-	echo
+    echo -n "$PGPOOL_RELOAD"
+    pid="`pidofproc -p $pidfile $PGPOOLDAEMON`"
+    if [ -n "$pid" ] ; then
+        $SU -l $PGPOOLUSER -c "$PGPOOLDAEMON -f $PGPOOLCONF reload" >> "$PGPOOLLOG" 2>&1 < /dev/null
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+            echo_success
+        else
+            echo_failure
+            script_result=1
+        fi
+    else
+        echo -n "pgpool is not running "
+        echo_failure
+        script_result=1
+    fi
+    echo
 }
 
 condrestart(){
@@ -173,7 +185,7 @@ case "$1" in
         stop
         ;;
   status)
-        status pgpool
+        status -p $pidfile pgpool
         script_result=$?
         ;;
   restart)
